name: CodeInt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4939869954250753
title: CodeInt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
