name: CodeInt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4939869954250753
title: CodeInt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74958506-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b3155'
    - '#5188a6'
    - '#8db8cb'
    - '#c6dae3'
    - '#000100'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
